#!/usr/bin/zsh

echo "==============================="
echo "===Updating the package list==="
echo "==============================="
sudo apt update

echo "================================"
echo "===Upgrading the package list==="
echo "================================"
sudo apt upgrade

echo "=============================================="
echo "===Installing additional packages==="
echo "=============================================="
sudo apt install -y --reinstall virtualbox-guest-x11 fish terminator gedit python3-pip vim-gtk3 gobuster sublist3r seclists pwncat updog

echo "========================="
echo "===Installing Rustscan==="
echo "========================="
wget -v https://github.com/RustScan/RustScan/releases/download/2.0.1/rustscan_2.0.1_amd64.deb
dpkg -i rustscan_2.0.1_amd64.deb

echo "===Script is complete.==="
